Repository davidho0403/breakfast-order-app, pull requests merged in 2023-05, with the labels that each got.

#51 Add section title component
  app/src/main/java/com/fcu/breakfast_order_app/SectionTitle.java
  app/src/main/res/drawable/br_section_title.xml
  app/src/main/res/layout/section_title.xml
Labels: frontend, component

#55 Add large button component
  app/src/main/java/com/fcu/breakfast_order_app/LargeButton.java
  app/src/main/res/drawable/br_large_button.xml
  app/src/main/res/layout/large_button.xml
Labels: frontend, component

#59 Add cart item component
  app/src/main/java/com/fcu/breakfast_order_app/CartItem.java
  app/src/main/res/layout/cart_item.xml
Labels: frontend, component

#67 Implement button with icon component
  app/src/main/java/com/fcu/breakfast_order_app/ButtonWithIcon.java
  app/src/main/res/drawable/current_order_btn_icon.xml
  app/src/main/res/drawable/history_order_btn_icon.xml
  app/src/main/res/drawable/logout_btn_icon.xml
  app/src/main/res/drawable/password_btn_icon.xml
  app/src/main/res/drawable/point_btn_icon.xml
  app/src/main/res/layout/button_with_icon.xml
Labels: frontend, component

#68 Implement the user information card component
  app/src/main/java/com/fcu/breakfast_order_app/UserInfoCard.java
  app/src/main/res/drawable/profile_image.png
  app/src/main/res/layout/user_info_card.xml
Labels: frontend, component

#69 Add back button
  app/src/main/res/drawable/arrow_left.xml
  app/src/main/res/layout/back_button.xml
Labels: frontend, component

#72 Implement the member info page
  app/src/main/java/com/fcu/breakfast_order_app/MemberInfoActivity.java
  app/src/main/res/layout/activity_member_info.xml
  app/src/main/res/layout/button_with_icon.xml
Labels: frontend, page

#62 Implement login page
  app/src/main/java/com/fcu/breakfast_order_app/LoginPageActivity.java
  app/src/main/res/layout/activity_login_page.xml
Labels: frontend, page

#63 Implement register page
  app/src/main/java/com/fcu/breakfast_order_app/RegisterPageActivity.java
  app/src/main/res/layout/activity_register_page.xml
Labels: frontend, page

#73 Add real product data and implement intent navigation feature
  app/src/main/AndroidManifest.xml
  app/src/main/java/com/fcu/breakfast_order_app/ProductBrowseActivity.java
  app/src/main/java/com/fcu/breakfast_order_app/ProductInfoActivity.java
  app/src/main/java/com/fcu/breakfast_order_app/Tab.java
  app/src/main/res/drawable/food_img10.png
  app/src/main/res/drawable/food_img11.png
  app/src/main/res/drawable/food_img12.png
  app/src/main/res/drawable/food_img13.png
  app/src/main/res/drawable/food_img14.png
  app/src/main/res/drawable/food_img15.png
  app/src/main/res/drawable/food_img16.png
  app/src/main/res/drawable/food_img17.png
  app/src/main/res/drawable/food_img18.png
  app/src/main/res/drawable/food_img19.png
  app/src/main/res/drawable/food_img20.png
  app/src/main/res/drawable/food_img21.png
  app/src/main/res/drawable/food_img22.png
  app/src/main/res/drawable/food_img23.png
  app/src/main/res/drawable/food_img24.png
  app/src/main/res/drawable/food_img25.png
  app/src/main/res/drawable/food_img26.png
  app/src/main/res/drawable/food_img27.png
  app/src/main/res/drawable/food_img28.png
  app/src/main/res/drawable/food_img29.png
  app/src/main/res/drawable/food_img30.png
  app/src/main/res/drawable/food_img31.png
  app/src/main/res/drawable/food_img32.png
  app/src/main/res/drawable/food_img33.png
  app/src/main/res/drawable/food_img34.png
  app/src/main/res/drawable/food_img35.png
  app/src/main/res/drawable/food_img36.png
  app/src/main/res/layout/activity_product_browse.xml
  app/src/main/res/layout/product_card.xml
Labels: frontend, page

#75 Implement the authentication feature and database
  app/src/main/AndroidManifest.xml
  app/src/main/java/com/fcu/breakfast_order_app/DatabaseHandler.java
  app/src/main/java/com/fcu/breakfast_order_app/LoginPageActivity.java
  app/src/main/java/com/fcu/breakfast_order_app/MemberInfoActivity.java
  app/src/main/java/com/fcu/breakfast_order_app/Nav.java
  app/src/main/java/com/fcu/breakfast_order_app/RegisterPageActivity.java
  app/src/main/res/drawable/user_icon.xml
  app/src/main/res/layout/activity_login_page.xml
  app/src/main/res/layout/activity_register_page.xml
  app/src/main/res/layout/button_with_icon.xml
  app/src/main/res/layout/nav.xml
Labels: sql

#77 Implement member info data fetching feature
  app/src/main/java/com/fcu/breakfast_order_app/DatabaseHandler.java
  app/src/main/java/com/fcu/breakfast_order_app/LoginPageActivity.java
  app/src/main/java/com/fcu/breakfast_order_app/MemberInfoActivity.java
  app/src/main/java/com/fcu/breakfast_order_app/RegisterPageActivity.java
  app/src/main/java/com/fcu/breakfast_order_app/UserInfo.java
  app/src/main/res/layout/activity_register_page.xml
Labels: page, sql
